---

- name: Install Ruby
  become: 'yes'
  apt: pkg=ruby-dev
  tags:
    - requirements

- name: Install front-end required packages.
  become: 'yes'
  gem: name={{ item.name }}
       version={{ item.version }}
       user_install=no
  with_items:
    - name: rb-inotify
      version: 0.9.10
    - name: compass
      version: 1.0.3
  tags:
    - requirements

- name: Configure Nginx site.
  become: 'yes'
  template: src={{ django_nginx_config }}
            dest=/etc/nginx/sites-enabled/{{ django_project_name }}.conf
  notify: reload nginx

- name: Configure Basic Auth.
  become: 'yes'
  template: src=basic_auth
            dest=/etc/nginx/{{ django_basic_auth_realm }}.auth
  notify: reload nginx
  when: django_basic_auth

- name: Compile CSS
  command: compass compile chdir={{ django_scss_path }}
  when: django_compile_css

- name: Collect Django static files.
  become: 'yes'
  become_user: '{{ django_user }}'
  django_manage: command=collectstatic
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: '{{ django_env }}'
  when: django_collectstatic

- name: Compress static files.
  become: 'yes'
  become_user: '{{ django_user }}'
  django_manage: command=compress
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: '{{ django_env }}'
  when: django_compressor_offline

- name: Install uWSGI
  become: 'yes'
  pip: name=uwsgi version={{ django_uwsgi_version }}

- name: Configure uWSGI init script
  become: 'yes'
  template: src=uwsgi_init
            dest=/etc/init/{{ django_project_name }}.conf
  when: ansible_distribution_release == 'trusty'
  notify: restart uwsgi

- name: Configure uWSGI init script (systemd)
  become: 'yes'
  template: src=uwsgi.service
            dest=/lib/systemd/system/{{ django_project_name }}.service
  when: ansible_distribution_release == 'bionic'
  notify: restart uwsgi (systemd)
