---

- name: Configure Nginx site.
  template: src=nginx_site.j2
            dest=/etc/nginx/sites-enabled/{{ django_project_name }}.conf
  notify: reload nginx

- name: Collect Django static files.
  sudo: no
  django_manage: command=collectstatic
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env

- name: Configure uWSGI process
  template: src=uwsgi_ini.j2
            dest={{ django_uwsgi_file }}
            group={{ django_user }}
            owner={{ django_user }}
