---

- name: Install front-end required packages.
  apt: pkg={{ item }}
       state=installed
  with_items:
    - ruby-compass
  tags:
    - requirements

- name: Configure Nginx site.
  sudo: yes
  template: src={{ django_nginx_config }}
            dest=/etc/nginx/sites-enabled/{{ django_project_name }}.conf
  notify: reload nginx

- name: Configure Basic Auth.
  sudo: yes
  template: src=basic_auth
            dest=/etc/nginx/{{ django_basic_auth_realm }}.auth
  notify: reload nginx
  when: django_basic_auth

- name: Compile CSS
  command: compass compile chdir={{ django_scss_path }}
  when: django_compile_css

- name: Collect Django static files.
  sudo_user: "{{ django_user }}"
  django_manage: command=collectstatic
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env
  when: django_collectstatic

- name: Compress static files.
  sudo_user: "{{ django_user }}"
  django_manage: command=compress
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env
  when: django_compressor_offline

- name: Install uWSGI
  pip: name=uwsgi version={{ django_uwsgi_version }}

- name: Configure uWSGI init script
  template: src=uwsgi_init
            dest=/etc/init/{{ django_project_name }}.conf
  notify: restart uwsgi
