---

- name: Configure Nginx site.
  sudo: yes
  template: src={{ django_nginx_config }}
            dest=/etc/nginx/sites-enabled/{{ django_project_name }}.conf
  notify: reload nginx

- name: Configure Basic Auth.
  sudo: yes
  template: src=basic_auth
            dest=/etc/nginx/{{ django_basic_auth_realm }}.auth
  notify: reload nginx
  when: django_basic_auth

- name: Collect Django static files.
  sudo_user: "{{ django_user }}"
  django_manage: command=collectstatic
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env
  when: django_collectstatic

- name: Configure uWSGI process
  template: src=uwsgi_ini.j2
            dest={{ django_uwsgi_file }}
            group={{ django_user }}
            owner={{ django_user }}
