---

- name: Install system-level requirements.
  become: yes
  apt: pkg={{ item }}
       state=installed
       update_cache=yes
  with_items:
    - "{{ django_system_packages }}"
    - "{{ django_system_packages_extra }}"
  tags:
    - requirements

- name: Create the project directory.
  become: yes
  file: state=directory
        path={{ django_project_path }}
        owner={{ django_user }}
        group={{ django_user }}

- name: Pull code from git repo.
  git: repo={{ django_repo }}
       dest={{ django_project_source }}
       accept_hostkey=yes
       key_file={{ django_deploy_key|default(omit) }}
       version={{ django_branch }}
  notify: reload uwsgi
  tags:
    - git

- name: Remove generated files
  command: git clean -fdx chdir={{ django_project_source }}
  tags:
    - git
    - skip_ansible_lint

- name: Install python requirements.
  pip: requirements={{ django_project_source }}/{{ django_requirements_file }}
       virtualenv={{ django_project_path }}
       state=present

- name: Configure Python PATH
  template: src=django.pth
            dest={{ django_project_path }}/lib/python2.7/site-packages/

- name: Fix source directory permissions
  file: state=directory
        path={{ django_project_source }}
        owner={{ django_user }}
        group={{ django_user }}
        recurse=yes

- name: Logging directory permissions
  become: yes
  file: state=directory
        path=/var/log/uwsgi
        owner={{ django_user }}
        group={{ django_user }}
        recurse=yes

- name: Virtualenv directory permissions
  become: yes
  file: state=directory
        path={{ django_project_path }}
        owner={{ django_user }}
        group={{ django_user }}
        recurse=yes

- name: Syncdb
  become_user: "{{ django_user }}"
  django_manage: command=syncdb
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: "{{ django_env }}"
  when: django_syncdb

- name: Run Migrations.
  become_user: "{{ django_user }}"
  django_manage: command=migrate
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: "{{ django_env }}"
  when: django_migrate

- name: Load Fixtures.
  become_user: "{{ django_user }}"
  django_manage: command=loaddata
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
                 fixtures="{{ django_fixtures | join(" ") }}"
  environment: "{{ django_env }}"
  when: django_fixtures

- include: front_end.yml
  when: django_setup_frontend

- name: Reload uWSGI process
  service: name={{ django_project_name }} state=reloaded
