---

- name: Install system-level requirements.
  apt: pkg={{ item }}
       state=installed
  with_items:
    - "{{ django_system_packages }}"
    - "{{ django_system_packages_extra }}"

- name: Create the project directory.
  file: state=directory
        path={{ django_project_path }}
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}

- name: Pull code from git repo.
  sudo: no
  git: repo={{ django_repo }}
       dest={{ django_project_source }}
       update=yes
       accept_hostkey=yes
       key_file={{ django_deploy_key }}
       version={{ django_branch }}
  when: django_deploy_key is defined
  notify: restart uwsgi
  tags:
    - git

- name: Pull code from git repo.
  sudo: no
  git: repo={{ django_repo }}
       dest={{ django_project_source }}
       update=yes
       accept_hostkey=yes
       version={{ django_branch }}
  when: not django_deploy_key
  notify: restart uwsgi
  tags:
    - git

- name: Install python requirements.
  sudo: no
  pip: requirements={{ django_project_source }}/requirements.txt
       virtualenv={{ django_project_path }}

- name: Run Migrations.
  sudo: no
  django_manage: command=migrate
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env

- include: front_end.yml
  when: django_setup_frontend
