---

- name: Install system-level requirements.
  apt: pkg={{ item }}
       state=installed
  with_items:
    - "{{ django_system_packages }}"
    - "{{ django_system_packages_extra }}"

- name: Create the project directory.
  file: state=directory
        path={{ django_project_path }}
        owner={{ ansible_ssh_user }}
        group={{ ansible_ssh_user }}

- name: Pull code from git repo.
  sudo: no
  git: repo={{ django_repo }}
       dest={{ django_project_source }}
       update=yes
       accept_hostkey=yes
       key_file={{ django_deploy_key }}
       version={{ django_branch }}
  when: django_deploy_key is defined
  tags:
    - git

- name: Pull code from git repo.
  sudo: no
  git: repo={{ django_repo }}
       dest={{ django_project_source }}
       update=yes
       accept_hostkey=yes
       version={{ django_branch }}
  when: not django_deploy_key
  tags:
    - git

- name: Install python requirements.
  sudo: no
  pip: requirements={{ django_project_source }}/requirements.txt
       virtualenv={{ django_project_path }}

- name: Configure Nginx site.
  template: src=nginx_site.j2
            dest=/etc/nginx/sites-enabled/{{ django_project_name }}.conf
  notify: reload nginx

- name: Configure uWSGI process
  sudo: no
  template: src=uwsgi_ini.j2
            dest={{ uwsgi_vassals_path }}/{{ django_project_name }}.ini

- name: Collect Django static files.
  sudo: no
  django_manage: command=collectstatic
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env

- name: Run Migrations.
  sudo: no
  django_manage: command=migrate
                 app_path={{ django_manage_path }}
                 settings={{ django_settings_module }}
                 virtualenv={{ django_project_path }}
  environment: django_env

- name: Reload uwsgi app
  sudo: no
  file: path={{ uwsgi_vassals_path }}/{{ django_project_name }}.ini
        state=touch
