---

- name: reload uwsgi
  become: 'yes'
  service: name={{ django_project_name }} state=reloaded

- name: restart uwsgi
  become: 'yes'
  service: name={{ django_project_name }} state=restarted

- name: restart uwsgi (systemd)
  become: 'yes'
  systemd: name={{ django_project_name }} state=restarted enabled=yes

- name: reload nginx
  become: 'yes'
  service: name=nginx state=reloaded
