---
- name: Converge
  hosts: all
  pre_tasks:
    - name: install sqlite
      become: true
      apt: name=sqlite
           update_cache=yes

  roles:
    - role: mnn.nginx

    - role: mnn.django
      become: false
      django_repo: 'https://github.com/bigjust/django-example.git'
      django_requirements_file: requirements/test.txt
      django_settings_module: config.settings.test
      django_user: ubuntu
